# fly.toml app configuration file generated for helldivers-2 on 2024-02-28T00:35:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'helldivers-2'
primary_region = 'ams'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'helldivers-2.fly.dev'
  PORT = '8080'
  RATE_LIMIT_MAX_REQUESTS = "100"
  RATE_LIMIT_INTERVAL = "300"
  ENABLE_IPV6 = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

  [[http_service.checks]]
    grace_period = "1s"
    interval = "60s"
    method = "GET"
    timeout = "5s"
    path = "/api/801/status"

[[vm]]
  memory = "512mb"
  size = 'shared-cpu-1x'
